# Generated by Django 3.2.9 on 2021-11-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reg_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_items', to='auction.player'),
        ),
    ]
